### ISSUE TITLE
December todo lists

### ISSUE THREAD

**Issue by qinwf** [rweekly/rweekly.org#132]
+ [x] update readme about the background of R Weekly
+ [x] a list of R Weekly current team members and introduction

**Comment by qinwf** [comment]
+ [ ] conf.rweekly.org more upcoming events
